name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Verify the format via Rustfmt
      run: cargo fmt --all --check --verbose
    - name: Lint via Clippy
      run: cargo clippy --no-deps --all-targets --all-features -- -D warnings

  doc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build the document
      run: cargo doc --no-deps --all-features

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: cargo build --all-targets --all-features
    - name: Execute tests
      run: cargo test --all-targets --all-features
