name: CI

on:
  push:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Verify the format via Rustfmt
      run: cargo fmt --all --check --verbose
    - name: Lint via Clippy
      run: cargo clippy --no-deps --all-targets --all-features -- -D warnings

  doc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build the document
      run: cargo doc --no-deps --all-features

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: cargo build --all-targets --all-features
    - name: Execute tests
      run: cargo test --all-targets --all-features
