name: CI

on:
  push:
  pull_request:

jobs:
  verify-format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Verify the format via Rustfmt
      run: cargo fmt --all --check --verbose

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Lint via Clippy
      run: cargo clippy --no-deps --all-targets --all-features -- -D warnings

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
